version: '3.3'
services:
    gate-app:
        image: xmonline/xm-gate:${IMAGE_TAG:-latest}
        networks:
            - xm2
        env_file:
            - ./env/gate-app.env
        ports:
            - 8080:8080
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
        secrets:
            - source: GATE_SPRING_DATASOURCE_PASSWORD
              target: SPRING_DATASOURCE_PASSWORD
        logging:
            driver: syslog
            options:
                tag: gate
                syslog-facility: local7
networks:
    xm2:
        driver: overlay
secrets:
    GATE_SPRING_DATASOURCE_PASSWORD:
        external: true
